### ISSUE TITLE
Zooming is a bit trippy

### ISSUE THREAD

**Issue by PikaDude** [8192px/8192px#3]
I find that zooming either zooms in a whole lot, or it sometimes zooms out so far you can't even see where the actual canvas is anymore. Could this be fixed? It's kind of annoying trying to find the canvas after zooming out.

**Comment by caspervonb** [comment]
cb822a21ef525b0cdca2a30a452c5debec783ed6 fixes it to scale, then translate (meaning no more jumping around when zooming).
8d650f2b3f67ef048955d684d3d5810035e19c5a scales by one from 5..1 which gives more range, from 5...100 still scales by 5 tho.

**Comment by PikaDude** [comment]
That's a lot better, thanks. The zoom is inverted but at least it is functional!
