### ISSUE TITLE
Recently colored pixels are flashing?

### ISSUE THREAD

**Issue by Jugemujugemugokonosurikire** [8192px/8192px#4]
These unusually light squares keep flashing between light and normal. Is there any way you can fix this? These squares were all recently placed.
![screenshot 2017-04-28 at 1 01 48 pm](https://cloud.githubusercontent.com/assets/26444889/25541066/e7e8a54e-2c12-11e7-9fcc-e70db4e36bfb.png)

**Comment by caspervonb** [comment]
Should be resolved now? I did something to kill a bot on the live server, during which i forgot to do something else which let a few pixels with lower opacity be placed, which i then fixed a minute later :smiley: 

I *think* that's it anyhow, can't spot that area on the live canvas.

**Comment by Jugemujugemugokonosurikire** [comment]
Okay. It seems to be fixed. Also, what is it about the color palette changing and 2 hour wait times? None of those things have happened as far as I'm aware.

**Comment by caspervonb** [comment]
I'll update those as-well.
